# Generated by Django 5.2.5 on 2025-08-09 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companydata',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='companydata',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
