# Generated by Django 5.2.5 on 2025-08-12 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_companydata_created_at_companydata_updated_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companydata',
            options={'ordering': ['company_name'], 'verbose_name': 'Company Data', 'verbose_name_plural': 'Companies Data'},
        ),
        migrations.AlterField(
            model_name='companydata',
            name='company_name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
