# Generated by Django 5.2.5 on 2025-08-11 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_models', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
    ]
