# Generated by Django 5.2.5 on 2025-08-11 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_models', '0002_appointment_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appointment_hour',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
