# Generated by Django 5.2.5 on 2025-08-12 03:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_models', '0004_patient_document_number_patient_maternal_lastname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='therapist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='base_models.therapist'),
        ),
    ]
