name: Run Django Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Django tests
        run: python manage.py test

      - name: Verificar Codigo HTML
        run: |
          npm install -g htmlhint
          echo '{"spec-char-escape": false}' > .htmlhintrc
          htmlhint "**/*.html" || exit 1

      - name: Verificar Codigo JavaScript
        run: |
          npm install -g eslint@8
          echo '{
            "env": { "browser": true, "es2021": true },
            "extends": "eslint:recommended",
            "parserOptions": { "ecmaVersion": 12, "sourceType": "module" },
            "rules": {}
          }' > .eslintrc.json
          eslint "**/*.js" || exit 1

      - name: Verificar Codigo CSS
        run: |
          npm install -g stylelint stylelint-config-standard
          echo '{ "extends": "stylelint-config-standard" }' > .stylelintrc.json
          stylelint "**/*.css" || exit 1
